## reading and preparing data
Sys.setlocale("LC_TIME", "C")
elect <- read.table("household_power_consumption.txt", sep = ";", header = T)
elect$Date <- strptime(elect$Date, format = "%d/%m/%Y")
elect$Date <- as.Date(elect$Date)
cn <- subset(elect, elect$Date ==  "2007-02-01")
cr <- subset(elect, elect$Date == "2007-02-02")
elect2 <- rbind(cn,cr)
elect2$datetime <- paste(elect2$Date, elect2$Time, sep = " ")
elect2$datetime <- strptime(elect2$datetime, format = "%Y-%m-%d %H:%M:%S")
elect2$Sub_metering_1<- as.numeric(as.character(elect2$Sub_metering_1))
elect2$Sub_metering_2<- as.numeric(as.character(elect2$Sub_metering_2))
elect2$Sub_metering_3<- as.numeric(as.character(elect2$Sub_metering_3))
elect2$Global_active_power <- as.numeric(as.character(elect2$Global_active_power))
elect2$Voltage <- as.numeric(as.character(elect2$Voltage))
elect2$Global_reactive_power <- as.numeric(as.character(elect2$Global_reactive_power))
## First graph
png(filename = "plot1.png",width = 480, height = 480, units = "px")
par(mar = c(4,4,2,2))
hist(elect2$Global_active_power, breaks = 12, xlab = "Global Active Power (kilowatts)", ylab = "Frequency", main = "Global Active Power", col = "red", xlim = c(0,6), ylim = c(0,1200))
dev.off()