## reading and preparing data
Sys.setlocale("LC_TIME", "C")
elect <- read.table("household_power_consumption.txt", sep = ";", header = T)
elect$Date <- strptime(elect$Date, format = "%d/%m/%Y")
elect$Date <- as.Date(elect$Date)
cn <- subset(elect, elect$Date ==  "2007-02-01")
cr <- subset(elect, elect$Date == "2007-02-02")
elect2 <- rbind(cn,cr)
elect2$datetime <- paste(elect2$Date, elect2$Time, sep = " ")
elect2$datetime <- strptime(elect2$datetime, format = "%Y-%m-%d %H:%M:%S")
elect2$Sub_metering_1<- as.numeric(as.character(elect2$Sub_metering_1))
elect2$Sub_metering_2<- as.numeric(as.character(elect2$Sub_metering_2))
elect2$Sub_metering_3<- as.numeric(as.character(elect2$Sub_metering_3))
elect2$Global_active_power <- as.numeric(as.character(elect2$Global_active_power))
elect2$Voltage <- as.numeric(as.character(elect2$Voltage))
elect2$Global_reactive_power <- as.numeric(as.character(elect2$Global_reactive_power))
## Third graph
png(filename = "plot3.png",width = 480, height = 480, units = "px")
plot(elect2$datetime, elect2$Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab = "",col = "black")
par(new = T)
plot(elect2$datetime, elect2$Sub_metering_2, type = "l", ylab = "", xlab = "", col = "red", axes = F, ylim = c(0, max(elect2$Sub_metering_1)))
par(new = T)
plot(elect2$datetime, elect2$Sub_metering_3, type = "l", ylab = "", xlab = "",col = "blue", axes = F, ylim = c(0, max(elect2$Sub_metering_1)))
par(new = T)
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black","red","blue"), lty = "solid", cex = 1)
par( new = F)
dev.off()